name: Build + Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy Functions App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      # Runs a single command using the runners shell
      # And of course we need to goto our functions folder to deploy
      - name: Install npm packages
        run: |
          cd functions
          npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
